context:
  name: essreduce
  version: "25.10.2"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essreduce-${{ version }}.tar.gz
  sha256: 871d924dc3568b5e19b9a482eb369171a2af53a72be6756d53640ea34837715f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - grow-nexus = ess.reduce.scripts.grow_nexus:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - sciline >=25.05.1
    - scipp >=25.04.0
    - scippneutron >=25.02.0
    - scippnexus >=24.11.0

tests:
  - python:
      imports:
        - ess
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - grow-nexus --help

about:
  summary: Common data reduction tools for the ESS facility
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/essreduce
  homepage: https://scipp.github.io/essreduce/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
